// Package testenv for creating mosquitto testing environment
package testenv

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"path"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/wostzone/wostlib-go/pkg/certsetup"
	"github.com/wostzone/wostlib-go/pkg/hubconfig"
)

const mosquittoConfigFile = "wost-mosquitto-test.conf"
const mqConfigTemplate = `
# Generated by SetupTestEnv. Do not edit.

log_type error
log_type warning
log_type information
log_dest stdout
persistence false
#acl_file {{.homeFolder}}/config/mosquitto.acl


#--- plugins and devices use certificates with MQTT
# MQTT over TLS/SSL
listener {{.certPortMqtt}}
require_certificate true
tls_version tlsv1.2
cafile {{.homeFolder}}/certs/caCert.pem
keyfile {{.homeFolder}}/certs/hubKey.pem
certfile {{.homeFolder}}/certs/hubCert.pem
# Password Authentication for users
#password_file {{.homeFolder}}/config/mosquitto-passwd


#--- consumers use username/pw with WebSockets over TLS/SSL
listener {{.unpwPortWS}}
protocol websockets
require_certificate false
tls_version tlsv1.2
cafile {{.homeFolder}}/certs/caCert.pem
keyfile {{.homeFolder}}/certs/hubKey.pem
certfile {{.homeFolder}}/certs/hubCert.pem
# Password Authentication for users
#password_file {{.homeFolder}}/config/mosquitto-passwd

`

// Createa mosquitto.conf file for testing
func CreateMosquittoConf(port int, homeFolder string) string {
	params := map[string]string{
		"homeFolder":   homeFolder,
		"certPortMqtt": fmt.Sprint(port),
		"unpwPortWS":   fmt.Sprint(port + 1), // FIXME, not like this :(
	}
	conf := hubconfig.SubstituteText(mqConfigTemplate, params)
	return conf
	// return ""
}

// Setup a test environment with a mosquitto broker on localhost for the given home folder
// This:
//  1. Create CA, server and client certificates if they don't exist
//  2. Generates a mosquitto configuration in /tmp
//  3. Launches a mosquitto broker for testing.
//
// Run TeardownTestEnv() to end the mosquitto broker
//  homeFolder is the home directory to run from
//  mqttPort is the port to listen on (required)
// Returns the mosquitto process
func Setup(homeFolder string, mqttPort int) (mqCmd *exec.Cmd) {
	hostnames := []string{"localhost"}
	if mqttPort == 0 {
		logrus.Panic("Missing mqtt port in test environment Setup")
		// mqttPort = 33100 // must match hub.yaml
		os.Exit(1)
	}
	certsFolder := path.Join(homeFolder, "certs")
	certsetup.CreateCertificateBundle(hostnames, certsFolder)

	logrus.Infof("--- Starting mosquitto broker ---")
	// mqCmd = Launch(mosqConfigPath)

	// mosquitto must be in the path to execute
	mosqConf := CreateMosquittoConf(mqttPort, homeFolder)
	mosqConfigPath := path.Join("/tmp", mosquittoConfigFile)
	err := ioutil.WriteFile(mosqConfigPath, []byte(mosqConf), 0644)
	if err != nil {
		logrus.Fatalf("Setup: Unable to write mosquitto config file: %s", err)
	}
	mqCmd = exec.Command("mosquitto", "-c", mosqConfigPath)
	// Capture stderr in case of startup failure
	mqCmd.Stderr = os.Stderr
	mqCmd.Stdout = os.Stdout
	mqCmd.Start()
	go func() {
		mqCmd.Wait()
		logrus.Infof("--- Mosquitto has ended ---")
	}()
	// Give mosquitto some time to start
	time.Sleep(10 * time.Millisecond)

	return mqCmd
}

// Teardown the test environment and stop the mosquitto broker
func Teardown(cmd *exec.Cmd) {
	cmd.Process.Kill()
}
